log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

http:
  routers:
    web-router:
      rule: "Host(`summitbloodsamples.rc.ucl.ac.uk`)"
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    web-secure-router:
      rule: "Host(`summitbloodsamples.rc.ucl.ac.uk`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certificates:
          - certFile: /etc/traefik/acme/summit-selfsigned.cert
            keyFile: /etc/traefik/acme/summit-selfsigned.key

  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
