version: '3.8'

volumes:
  production_postgres_data:
  production_postgres_data_backups:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: summit_blood_samples_production_django
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - type: bind
        source: ./uploads
        target: /uploads
      - type: bind
        source: ./staticfiles
        target: /static
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: summit_blood_samples_production_postgres
    volumes:
      - type: volume
        source: production_postgres_data
        target: /var/lib/postgresql/data
      - type: volume
        source: production_postgres_data_backups
        target: /backups
    env_file:
      - ./.envs/.production/.postgres

  pgadmin:
    build:
      context: .
      dockerfile: ./compose/production/pgadmin/Dockerfile
    image: summit_blood_samples_production_pgadmin
    env_file:
      - ./.envs/.production/.pgadmin
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: summit_blood_samples_production_nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:2345:2345"
    volumes:
      - type: bind
        source: ./compose/production/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./compose/production/nginx/certs
        target: /etc/nginx/certs
      - type: bind
        source: ./compose/production/nginx/snippets
        target: /etc/nginx/snippets
      - type: bind
        source: ./staticfiles
        target: /static
    depends_on:
      - django
      - pgadmin
