# Generated by Django 3.0.8 on 2020-08-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_sample', '0003_auto_20200821_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedaliquots',
            old_name='SampleId',
            new_name='ParentID',
        ),
        migrations.RenameField(
            model_name='processedaliquots',
            old_name='SampleIdFile',
            new_name='ProcessedReportSampleId',
        ),
        migrations.AddField(
            model_name='processedreport',
            name='SiteHeld',
            field=models.CharField(choices=[(0, 'UK Biocentre')], default=0, max_length=1),
        ),
    ]
