# Generated by Django 3.0.8 on 2020-09-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_sample', '0004_auto_20200828_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedaliquots',
            old_name='ProcessedReportSampleId',
            new_name='AliquotId',
        ),
    ]
