# Generated by Django 3.0.8 on 2020-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_sample', '0005_auto_20200901_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestrecords',
            name='Site',
            field=models.CharField(choices=[(0, 'FMH'), (1, 'KGH'), (2, 'MEH'), (3, 'UCLH')], max_length=1),
        ),
        migrations.AlterField(
            model_name='processedaliquots',
            name='SampleType',
            field=models.CharField(choices=[(0, 'RBC'), (1, 'Plasma'), (2, 'BuffyCoat')], max_length=1),
        ),
    ]
