# Generated by Django 3.0.8 on 2020-09-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_sample', '0006_auto_20200903_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptrecords',
            name='Clinic',
            field=models.CharField(choices=[(0, 'FMH'), (1, 'KGH'), (2, 'MEH'), (3, 'UCLH')], max_length=1),
        ),
    ]
