# Generated by Django 3.0.8 on 2021-09-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_sample', '0007_auto_20200914_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedaliquots',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
